disabled = false
locale = "en"
label = "English"
weight = 1
title = "Fabians Portfolio 3. Semester 2026"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "Fabian Strøm"
image = "images/profile.jpeg"
headline = "Datamatiker – 3. semester"
bio = "Portfolio for mit 3. semester"

links = [
  { github = "https://github.com/Fabian-str" }
]